.TH pattern2eps 1  "v2; Apr 29, 2007" 
.SH NAME

pattern2eps - Generate encapsulated postscript output from a fragrep pattern

.SH SYNOPSIS
.B aln2pattern [\-m] <alignment file>

.SH DESCRIPTION

pattern2eps reads a fragrep pattern as produced (and eventually
manually edited) by aln2pattern. 

.SH OPTIONS
.TP
\-L <line_length> modify line length. Default value is 100.

.SH OUTPUT

Output is written to the file pattern2eps.eps in the current working
directory.


.PP


.SH SEE ALSO

fragrep, aln2pattern

.SH AUTHORS
Axel Mosig, CAS-MPG Partner Institute for Computational Biology,
Shanghai, China

Peter F. Stadler, Katrin Sameith, Bioinformatics Group,
University of Leipzig, Germany. 

Email:axel (at) picb.ac.cn

.SH URL
www.bioinf.uni-leipzig.de/Software/fragrep

